### ISSUE TITLE
Make module imports transparent

### ISSUE THREAD

**Issue by fridex** [gofed/lib#7]
It is not possible to use module in a generic manner; reproducer:

```
$ git clone https://github.com/gofed/lib gofedlib
$ cat > test.py <<EOF
# extract API and dependencies

from gofedlib.go.functions import api, project_packages
from gofedlib.types import ExtractionError
import logging

source_code_directory = "~/Golang/etcd/etcd-5e6eb7e19d6385adfabb1f1caea03e732f9348ad"

try:
    etcd_api = api(source_code_directory)
    etcd_packages = project_packages(source_code_directory)
except ExtractionError as e:
    logging.error("Unable to extract %s: %s" % (source_code_directory, e))
    exit(1)

# print list of defined packages in etcd
print "Defined packages"
for package in etcd_packages["packages"]:
    print package
print ""

# print list of defined exported functions in etcd
print "Defined functions"
for package in etcd_api:
    print package["package"]
    for func in package["functions"]:
        print "\t%s" % func["name"]
print ""
EOF

$ python test.py
Traceback (most recent call last):
  File "./test.py", line 3, in <module>
    from gofedlib.go.functions import api, project_packages
  File "/tmp/gofedlib/go/functions.py", line 1, in <module>
    from .symbolsextractor.extractor import GoSymbolsExtractor
  File "/tmp/gofedlib/go/symbolsextractor/extractor.py", line 4, in <module>
    from lib.utils import getScriptDir, runCommand
ImportError: No module named lib.utils
```

**Comment by ingvagabund** [comment]
1) need to set PYTHONPATH to point to directory where you cloned gofed_lib repository is
2) the cloned directory has to be named `lib`

**Comment by ingvagabund** [comment]
Readme.md has to be updated.

**Comment by fridex** [comment]
> 1) need to set PYTHONPATH to point to directory where you cloned gofed_lib repository is
> 2) the cloned directory has to be named lib

This does not conform to a library design. This should be transparent without additional hacks.
